name: ${PROJECT_NAME:-your-project-name}

services:
  joomla:
    build:
      context: .
      args:
        JOOMLA_VERSION: ${JOOMLA_VERSION:-latest}
      dockerfile: resources/config/Dockerfile
    container_name: ${CONTAINER_PREFIX:-joomla}-app
    restart: unless-stopped
    ports:
      - ${WEB_PORT:-8080}:80
      - 9000:9000
    extra_hosts:
      host.docker.internal: host-gateway
    environment:
      - JOOMLA_DB_HOST=joomladb
      - JOOMLA_DB_NAME=${DB_NAME:-joomla}
      - JOOMLA_DB_PASSWORD=${DB_PASSWORD:-examplepass}
      - JOOMLA_DB_USER=${DB_USER:-joomla}
      - JOOMLA_SITE_NAME=${JOOMLA_SITE_NAME:-Joomla}
      - JOOMLA_ADMIN_USER=${JOOMLA_ADMIN_USER:-Joomla Admin}
      - JOOMLA_ADMIN_USERNAME=${JOOMLA_ADMIN_USERNAME:-admin}
      - JOOMLA_ADMIN_PASSWORD=${JOOMLA_ADMIN_PASSWORD:-admin@secured}
      - JOOMLA_ADMIN_EMAIL=${JOOMLA_ADMIN_EMAIL:-joomla@example.com}
      - XDEBUG_CONFIG=remote_host=host.docker.internal
    depends_on:
      joomladb:
        condition: service_healthy
    user: ${UID:-1000}:${GID:-1000}
    volumes:
      - ./${JOOMLA_FOLDER:-joomla_data}:/var/www/html
      - ./src:/var/www/src
      - ./resources/config/php/php.ini:/usr/local/etc/php/php.ini
      - ./resources/config/apache/000-default.conf:/etc/apache2/sites-available/000-default.conf
    networks:
      - joomla_dev_network

  joomladb:
    image: mysql:${MYSQL_VERSION:-latest}
    container_name: ${CONTAINER_PREFIX:-joomla}-db
    restart: on-failure
    ports:
      - ${MYSQL_PORT:-3306}:3306
    environment:
      - MYSQL_DATABASE=${DB_NAME:-joomla}
      - MYSQL_PASSWORD=${DB_PASSWORD:-examplepass}
      - MYSQL_RANDOM_ROOT_PASSWORD='1'
      - MYSQL_USER=${DB_USER:-joomla}
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 2s
      timeout: 20s
      retries: 10
    user: ${UID:-1000}:${GID:-1000}
    volumes:
      - ./${DB_FOLDER:-db_data}:/var/lib/mysql
    networks:
      - joomla_dev_network

  composer:
    image: composer:${COMPOSER_VERSION:-2.8.12}
    container_name: ${CONTAINER_PREFIX:-joomla}-composer
    command: [ "composer", "update" ]
    volumes:
      - ./resources:/app

networks:
  joomla_dev_network:
